version: '3.8'
services:
  mongo: 
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: team2
      MONGO_INITDB_ROOT_PASSWORD: team2
      MONGO_INITDB_DATABASE: rental_houses
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
volumes:
  mongodata:
    driver: local