name: TEST CI/CD Step
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Demo Build
        run: echo Hello Retool

      - name: Alerts
        uses: twilio-labs/actions-sms@v1
      - name: "Sending SMS OTP"
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: "+19164680573"
          toPhoneNumber: "+84818492109"
          message: "Hello from Twilio"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
